name: CI

on: [push]

jobs:
  test:
    name: Check Schema
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - uses: tvvignesh/graphql-inspector@introspection-support
        with:
          schema: "master:schema.json"
